steps:
  - id: "dev branch"
    name: 'hashicorp/terraform:1.0.0'
    env:
    - 'BRANCH=$(git rev-parse --abbrev-ref HEAD)'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo $BRANCH
          pwd
          cd demo
          ls
         
          if [ "$BRANCH" == "master"  ]; then
            cd demo/$BRANCH_NAME
            docker build -t demo:0.0.1 .
            docker tag demo:0.0.1 gcr.io/qwiklabs-gcp-01-dc9e9c930753/demo:0.0.1
            docker push gcr.io/qwiklabs-gcp-01-dc9e9c930753/demo:0.0.1
            gcloud run deploy dev-demo --image gcr.io/qwiklabs-gcp-01-dc9e9c930753/demo:0.0.1 --platform managed --region us-central1 --allow-unauthenticated --port 8000
          fi

  - id: "prod branch"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/qwiklabs-gcp-04-c23dcfc9e2fc/multi-br:0.0.1', 'dev/.']
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['push', 'gcr.io/qwiklabs-gcp-04-c23dcfc9e2fc/multi-br:0.0.1']
